### ISSUE TITLE
Feature: Recursive

### ISSUE THREAD

**Issue by kfoxton** [dangphuc2470/Creation_Date_Changer#1] opened 2024-07-15 15:45 UTC
Hey, thanks for making this tool, its helping me out lots!

I was wondering if it would be possible to have it take a directory and it scans though all of the subdirectories for files to apply to, instead of just individual files?

**Comment by dangphuc2470** [comment] 2024-07-17 08:45
Thanks for your interest in my tool! 

Based on your request, I've added folder scanning with subfolders. However, the current limitation is that the tool can only replace one naming format at a time. So I created a combobox to display the naming format groups and created an assign button to assign to the text box below to improve user experience while replacing manually.

Try it and let me know if any errors occur. Just in case, I recommend starting with a small photo folder or making a backup first because I'm not sure if I tested it thoroughly enough.

![screenshot2](https://github.com/user-attachments/assets/5c32bfe3-5e96-4dcd-af6c-97f4d4e065c7)

**Comment by kfoxton** [comment] 2024-07-17 13:14
Hey, 
Thanks for making an update. 

I gave it a try, and it looks like the grouping is not working correctly. All of my file names are in the same format, but it seems to be grouping them oddly.  My files are in the scheme of yyyymmdd_hhmmss_rrrrrrrr.extention but as you can see in the screenshot, when scanning a directory with 12 subdirectories, it seems to find hundreds of file name formats.

![image](https://github.com/user-attachments/assets/b0809b3a-b7f6-481f-8f0e-3aa8dc36f5fb)

**Comment by dangphuc2470** [comment] 2024-07-17 14:14
Ah, I see the problem is because I didn't take into account that the suffix characters (The HEX number at the end in your example, not the extension) include both letters and numbers. I can't think of any way to handle that suffix automatically, so I've added an option to ignore the characters at the end. I don't know if it affects other naming formats. Please try it again and let me know
![image](https://github.com/user-attachments/assets/333899e0-94ef-4b85-a9a1-21c53ad60d7e)

**Comment by kfoxton** [comment] 2024-07-17 16:08
Hey, I tried the new version and setting the ignore value and re-selecting the folder again, doesn't seem to change the options found.  Would it be better to just disregard anything after the last . so that the file extention is just fully ignored, if that is the cause of the issue?


![image](https://github.com/user-attachments/assets/1f1d506b-faf0-4f24-bb23-2745586f9986)
![image](https://github.com/user-attachments/assets/e9751420-cc01-46ca-9c71-e9c8c1734001)

**Comment by dangphuc2470** [comment] 2024-07-17 17:02
I have ignored the extensions so you don't need to care about it, and you need to enter the number 8 which is the number of HEX charaters at the end of the name (which make my tool indentify it as different group), like the example above I named the same as your files.

**Closed as completed** 2024-07-22 16:33 UTC

**Comment by kfoxton** [comment] 2024-07-23 20:10
Sorry for the delay in getting back to you. I verified it works as expected. Thanks again for making this tool!
